### ISSUE TITLE
vim split in open buffer errors

### ISSUE THREAD

**Issue by sfahlberg** [thoughtbot/pick.vim#10]
I'm trying to open up a list of the open buffers that I can subsequently open in a vsplit. The functionality exists in ctrl-p and I'd love to see it here.

I tried running 

:call PickCommand(s:BufferListCommand(), "", ":vsplit")<CR>

but I get the following errors:

E120: Using <SID> not in a script context: s:BufferListCommand
E116: Invalid arguments for function PickCommand

**Comment by teoljungberg** [comment]
Hi @sfahlberg, and thanks for opening this issue!

I think #11 is a different approach to resolving this issue than what you brought up here. I opened up #12 to make `BufferListCommand` a public function, which means that you can create your own functions to extend pick.vim.

Could you try it out, and let us know what you think?

**Comment by teoljungberg** [comment]
As discussed in #11, I opened #12 to allow further customization into pick.vim.

Since that has been merged, I'm closing this. Thanks for spearheading this!
