### ISSUE TITLE
Pick file or pick file vertical split

### ISSUE THREAD

**Issue by hdtafur** [thoughtbot/pick.vim#17]
Hello! I wanted to know if it's possible to view one's files and _then_ select to open by vertical split or normally. At the moment, I have to chose beforehand which way to open the file, with with `PickFileVerticalSplit()` or with `PickFile()`. With ctrlp, I loved having the freedom of choosing this after getting the list of files.

I'm curious to know if this can be done by personal customization or if this is presently available. Thanks!

**Comment by teoljungberg** [comment]
Sadly we can't, pick works by shelling out to your terminal and then giving the result to vim and performing an action on the result. 

Hope that answers your question.

**Comment by hdtafur** [comment]
I see. Thanks for the response!
