### ISSUE TITLE
PickFileTab when a tab is already open for that file

### ISSUE THREAD

**Issue by jussi-kalliokoski** [thoughtbot/pick.vim#23]
People like me tend to gather a significant amount of tabs open and forget that one of them already has the file they want to edit, leading to a lot of duplicated tabs. Editors like atom handle deduplicating for you so if you fuzzy open a new tab it goes to the existing one instead, if available. Might be quite nice to support that functionality in pick.vim as well.

P.S. Thanks for this plugin, seeing it in action made me switch back to vim again.  🎉  🙏

**Comment by calleluks** [comment]
Hey @jussi-kalliokoski, I'm glad you like the plugin!

I'm not entirely sure how to implement one but if you had a command to find a tab by filename or opens a new one you could use it with pick.vim like so:

```
nnoremap <Leader>t :call PickCommand("git ls-files . --cached --exclude-standard --others", "", ":FindOrOpenTab", 1) <CR>
```

**Comment by jussi-kalliokoski** [comment]
Thanks @calleerlandsson ! Managed to get it working by doing a viml implementation (well, close enough) of the `:tab pick` command in gVIM: https://github.com/jussi-kalliokoski/dotfiles/commit/25b70ab171dc976116fb92cc50d0d5bb12d27223 :)
