### ISSUE TITLE
PickTag() fails when vim 'tags' variable includes stop directories (upwards search)

### ISSUE THREAD

**Issue by ghost** [thoughtbot/pick.vim#4]
The PickTag() function treats the vim 'tags' variable as a comma separated list of simple tag files. And it calls 'cat' on this list to generate input for 'pick'. However, if the 'tags' variable includes stop directories (see vim help 'file-searching) they are appended with a ';' and this will cause the expression returned by TagCommand() to be wrong. 

E.g. say the 'tags' variable is 'tags = ./tags;' with ';' appended to indicate upwards search until the root directory. That will make the expression returned by TagCommand() to be:

cat ./tags; 2> /dev/null | awk -F$'\t' '{print $1}' | sort -u | grep -v '^!'

and the final command piping into 'pick'

cat ./tags; 2> /dev/null | awk -F$'\t' '{print $1}' | sort -u | grep -v '^!' | pick

But the ';' after 'cat ./tags' will then be treated by the shell as a command separator, so now the first command cat's the tags file and the second command calls pick but with no valid input. I guess somehow the 'tags' variable should be expanded/parsed to a proper list of simple file names without search patterns.

**Comment by ghost** [comment]
Seems that the builtin tagfiles() function will do the trick. From vim help :

tagfiles()      Returns a List with the file names used to search for tags
                for the current buffer.  This is the 'tags' option expanded.

**Comment by ghost** [comment]
The following fix in the TagCommand() function seems to do the trick:

```
function! s:TagCommand()
-  let l:tag_files = join(split(&tags, ","), " ")
+  let l:tag_files = join(tagfiles(), " ")
```

**Comment by calleluks** [comment]
Thanks for reporting this @hejersbo! Your solution looks great. I'll merge #5 right away.
